### ISSUE TITLE
compilation error with TBB

### ISSUE THREAD

**Issue by chenxuhao** [pdclab/peregrine#1] opened 2020-05-13 01:26 UTC
Hi,
I got this error when doing make:

g++ -c core/DataGraph.cc -o core/DataGraph.o -O3 -std=c++2a -Wall -Wextra -Wpedantic -fPIC -fconcepts -I/net/ohm/export/cdgc/cxh/peregrine/core/
In file included from /org/centers/cdgc/sw/gcc-9.2.0/include/c++/9.2.0/pstl/parallel_backend.h:14,
                 from /org/centers/cdgc/sw/gcc-9.2.0/include/c++/9.2.0/pstl/algorithm_impl.h:25,
                 from /org/centers/cdgc/sw/gcc-9.2.0/include/c++/9.2.0/pstl/glue_execution_defs.h:52,
                 from /org/centers/cdgc/sw/gcc-9.2.0/include/c++/9.2.0/execution:32,
                 from core/Graph.hh:4,
                 from core/DataGraph.cc:13:
/org/centers/cdgc/sw/gcc-9.2.0/include/c++/9.2.0/pstl/parallel_backend_tbb.h:28:2: error: #error Intel(R) Threading Building Blocks 2018 is required; older versions are not supported.
   28 | #error Intel(R) Threading Building Blocks 2018 is required; older versions are not supported.
      |  ^~~~~
/org/centers/cdgc/sw/gcc-9.2.0/include/c++/9.2.0/pstl/parallel_backend_tbb.h: In function ‘void __pstl::__par_backend::__parallel_for(_ExecutionPolicy&&, _Index, _Index, _Fp)’:
/org/centers/cdgc/sw/gcc-9.2.0/include/c++/9.2.0/pstl/parallel_backend_tbb.h:99:10: error: ‘tbb::this_task_arena’ has not been declared
   99 |     tbb::this_task_arena::isolate([=]() {
      |          ^~~~~~~~~~~~~~~

Does that mean I need to install TBB? Which TBB version should I install? I have both gcc 9.2.0 and 9.3.0 installed.

Thank you!

**Comment by kjamsh** [comment] 2020-05-13 04:44
Hi!

Did you run

```source tbb2019/bin/tbbvars.sh intel64```

before trying to compile? Yes, as the error indicates you need TBB for some C++17 features we use.
This repo has a copy of tbb2019 included.

**Comment by chenxuhao** [comment] 2020-05-14 03:15
> Hi!
> 
> Did you run
> 
> `source tbb2019/bin/tbbvars.sh intel64`
> 
> before trying to compile? Yes, as the error indicates you need TBB for some C++17 features we use.
> This repo has a copy of tbb2019 included.

Thank you so much. That solves my problem.
I tried to convert this graph from SNAP:
https://snap.stanford.edu/data/soc-LiveJournal1.html

This it the edgelist I downloaded:
$ head data/soc-LiveJournal1.txt 
\# Directed graph (each unordered pair of nodes is saved once): soc-LiveJournal1.txt 
\# Directed LiveJournal friednship social network
\# Nodes: 4847571 Edges: 68993773
\# FromNodeId	ToNodeId
0	1
0	2
0	3

However, when I convert it:
$ bin/convert_to_binary.sh data/soc-LiveJournal1.txt 4847571 data/livej

the graph file generated is not correct:
$ ./bin/count data/livej/ 4-cliques 56
No label file
Finished reading datagraph: |V| = 4846609 |E| = 42851237
Segmentation fault (core dumped)

What am I missing? This is also happening for friendster:

$ head data/com-friendster.ungraph.txt 
\# Undirected graph: ../../data/output/friendster.txt
\# Friendster
\# Nodes: 65608366 Edges: 1806067135
\# FromNodeId	ToNodeId
101	102
101	104
101	107

$ bin/convert_to_binary.sh data/com-friendster.ungraph.txt 130000000 data/friendster
Size of file is 32364651776
Time Taken for memory mapping the file : 3496538[µs]
degree map calculated per thread
Time Taken degree calculation per thread 834480173[µs]
Time Taken global degree calculation  358270152[µs]
degree map calculated
Number of vertices : 65608366
Total Degree : 3612134270
data graph  created
Time Taken for populating data  94925188[µs]
data graph populated
degree map sorted
Biggest Degree of the vertex : 71768986 5214
Time Taken for writing data to disk  16995967[µs]
Edge Count : 3612134270 Data Count : 3808959371
Total Time Taken : 1319939271[µs]

$ ./bin/count data/friendster/ 3-cliques 56
No label file
Finished reading datagraph: |V| = 65608366 |E| = 1806067135
Segmentation fault (core dumped)

Any idea?

**Comment by kjamsh** [comment] 2020-05-14 16:56
Do you mind telling me what branch each command is running on and whether you've fetched the latest sources?

I couldn't reproduce your segfault with the Friendster graph using the latest `master` or `eurosys20-experiments` branches. `soc-LiveJournal` won't work as expected in any case, because Peregrine doesn't support directed datasets yet (I'll be sure to document this clearly in the README).

The `master` branch uses a new data format (and converter). If you converted the data on `master` a couple of weeks ago, then pulled, you'd have to re-convert the data using the new converter. Maybe this explains the problem?

Meanwhile, the `eurosys20-experiments` and `eurosys20-prg-u` branches still use the same data format. So any data converted in `master` will be incompatible with the reproduction branches, and vice versa.

Let me know if this solves your problem!

**Comment by chenxuhao** [comment] 2020-05-14 18:31
> Do you mind telling me what branch each command is running on and whether you've fetched the latest sources?
> 
> I couldn't reproduce your segfault with the Friendster graph using the latest `master` or `eurosys20-experiments` branches. `soc-LiveJournal` won't work as expected in any case, because Peregrine doesn't support directed datasets yet (I'll be sure to document this clearly in the README).
> 
> The `master` branch uses a new data format (and converter). If you converted the data on `master` a couple of weeks ago, then pulled, you'd have to re-convert the data using the new converter. Maybe this explains the problem?
> 
> Meanwhile, the `eurosys20-experiments` and `eurosys20-prg-u` branches still use the same data format. So any data converted in `master` will be incompatible with the reproduction branches, and vice versa.
> 
> Let me know if this solves your problem!





Thanks for your reply. 
Is the text file "com-friendster.ungraph.txt" the right input file for the converter?
Follow your instructions, this is what I did just now which still produces the error:

```
$ git clone https://github.com/pdclab/peregrine
$ cd peregrine
$ git checkout eurosys20-experiments
$ source tbb2019/bin/tbbvars.sh intel64
$ mkdir bin
$ make -j count fsm existence-query
$ make convert_to_binary
$ mkdir data/friendster
$ bin/convert_to_binary.sh data/com-friendster.ungraph.txt 130000000 data/friendster
$ ./bin/count data/citeseer/ 3-cliques 56

Finished reading datagraph: |V| = 3264 |E| = 4536
[1-2][1-3][2-3] finished after 0.004456s
-------
all patterns finished after 0.004724s
[1-2][1-3][2-3]: 1166

$ ./bin/count data/friendster/ 3-cliques 56
No label file
Finished reading datagraph: |V| = 65608366 |E| = 1806067135
Segmentation fault (core dumped)
```

Note that in master it is "convert_data" instead of "convert_to_binary".
Here is the compilation error I got when I pull another copy of the repo and compile in master:

```
$ source tbb2019/bin/tbbvars.sh intel64
$ mkdir bin
$ make -j count fsm existence-query
$ make convert_data
g++ -o bin//convert_data core/convert_data.cc core/utils.o -lpthread -ltbb -latomic -O3 -std=c++2a -Wall -Wextra -Wpedantic -fPIC -fconcepts -I/workspace/cxh/peregrine/core/
/tmp/ccEv0HEX.o: In function `main':
convert_data.cc:(.text.startup+0x70e): undefined reference to `tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
convert_data.cc:(.text.startup+0x8f4): undefined reference to `tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
convert_data.cc:(.text.startup+0xa9d): undefined reference to `tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
convert_data.cc:(.text.startup+0xbbc): undefined reference to `tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
convert_data.cc:(.text.startup+0xfa3): undefined reference to `tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
collect2: error: ld returned 1 exit status
make: *** [convert_data] Error 1

```

**Comment by chenxuhao** [comment] 2020-05-14 20:06
BTW, should the vertex ID in the input edgelist file for the converter start from 0 or 1?

**Comment by kjamsh** [comment] 2020-05-14 20:36
Hi Xuhao,

The vertex ID's can start from any non-negative integer. 0, 1, 500 are all okay.

I'm still trying to reproduce your segfault. It's particularly strange that the provided citeseer graph works, but the generated friendster graph does not, since the citeseer graph is generated the same way! Does `./convert_to_binary.sh` finish exit normally? Perhaps the concatenation of the intermediate data files fails due to insufficient disk space or something? I could also send you my copy of the generated data perhaps, to see if the dataset is the problem.

I'm also perplexed by the compiler error. What distribution of Linux is this on? I'd like to try to replicate it as well.

Thanks

**Comment by kjamsh** [comment] 2020-05-15 01:04
Hi Xuhao,

I believe I've fixed the compilation issue on `master`, you should be able to `make convert_data` now. I'm still trying to reproduce the segfault on Friendster.

Let me know if the problems persist!

**Comment by chenxuhao** [comment] 2020-05-16 12:33
> Hi Xuhao,
> 
> I believe I've fixed the compilation issue on `master`, you should be able to `make convert_data` now. I'm still trying to reproduce the segfault on Friendster.
> 
> Let me know if the problems persist!

Hi Kasra,
Thank you for your help. 
./convert_to_binary.sh does finish normally on centos. The only problem happens when executing apps.
It seems like this converter works on Ubuntu 18.04. However since I only have a desktop installed Ubuntu, it can not generate friendster due to limited memory. But I tried small graphs and they worked. It could be useful if you can send me your copy of the generated friendster.

**Comment by kjamsh** [comment] 2020-06-19 20:45
Hi Xuhao,

From our email discussions, this issue seems to be resolved, so I'm going to close it. If I'm mistaken, or if you run into more problems please don't hesitate to open another issue!

Thanks again for your interest.

**Closed as completed by kjamsh** 2020-06-19 20:45 UTC
